name: Docker Image CI

on:
  push:
    branches: [ bar ]
  pull_request:
    branches: [ bar ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file 11.2.0.4/Dockerfile --tag my-image-name:$(date +%s)
